

Thaliz_PresetMessages = {
	[1] = {
		["name"] = "Classic",
		["description"] = "World of Warcraft Classic boss quotes",
		["messages"] = {
			"(Ressing) THIS CANNOT BE!!! %s, deal with these insects.",
			"(Ressing) I'm keeping my eye on you, %s!",
			"(Ressing) %s, fill me with your RAGE!",
			"(Ressing) Fleeing will do you no good, %s!",
			"(Ressing) Master %c %s, continue the fight!",
			"(Ressing) Perhaps you'll need another lesson in pain, %s!",
			"(Ressing) Too soon, %s - you have died too soon!",
			"(Ressing) You have failed me, %s! Justice is met, indeed!",
			"(Ressing) Forgive me %s, your death only adds to my failure.",
			"(Ressing) Let your death serve as an example, %s!",
			"(Ressing) Only flesh and bone. %cs are such easy prey, %s!",
			"(Ressing) Your friends will abandon you, %s!",
			"(Ressing) Shhh, %s... it will all be over soon.",
			"(Ressing) Slay %s in the masters name!",
			"(Ressing) Rise, %s! Rise and fight once more!",
			"(Ressing) You should have stayed home, %s!",
			"(Ressing) Death is the only escape, %s.",
			"(Ressing) The first res goes to %s! Anyone care to wager?",
			"(Ressing) No more play, %s?",
			"(Ressing) %s, you are too late... I... must... OBEY!",
		},
	},
	[2] = {
		["name"] = "TBC",
		["description"] = "The Burning Crusade boss quotes",
		["messages"] = {
			"(Ressing) Perhaps you would rather test yourself against a more formidable opponent, %s",
			"(Ressing) Come, gentle night; and give me back my %s!",
			"(Ressing) You rang, %s?",
			"(Ressing) %s is no longer op... er... ation... al.",
			"(Ressing) Please, accept this humble offering, oh great %s.",
			"(Ressing) You've wasted enough of my time... let these games be finished, %s!",
			"(Ressing) Your greed, your foolishness has brought you to this end, %s.",
			"(Ressing) You will not defeat the Hand of %s!",
			"(Ressing) Let us see how your nerves hold up against the Darkener, %s.",
			"(Ressing) All of your efforts have been in vain, %s!",
			"(Ressing) %s has returned to finish what was begun so many years ago.",
			"(Ressing) Is this it, %s? Is this all the fury you can muster?",
			"(Ressing) You play, you pay, %s!",
			"(Ressing) %s, You can have anything you desire... for a price.",
			"(Ressing) So much time has passed. %s have a lot of catching up to do...",
			"(Ressing) I did not wish to lower myself by ressing %s, but you leave me little choice!",
			"(Ressing) Your overconfidence will be your undoing! %s, lend me your strength!",
			"(Ressing) %s ... Be gone trifling %r. I'm in control now.",
			"(Ressing) The expendible have perished... So be it! Now I shall succeed where %s could not!",
			"(Ressing) Your luck has run its course, %s!",		
		},
	},
	[3] = {
		["name"] = "Lich King",
		["description"] = "Wrath of the Lich King boss quotes",
		["messages"] = {
			"(Ressing) %s - where to go? What to do? So many choices that all end in pain, end in death.",
			"(Ressing) Wait %s ... I remember you ... from the mountains.",
			"(Ressing) Listen, %s... Listen for the voice of your master. He calls to you now.",
			"(Ressing) Enough, %s! I grow tired of these distractions!",
			"(Ressing) Arise, %s of the iron crucible! The Maker's will be done!",
			"(Ressing) %s have strayed too far, wasted too much time!",
			"(Ressing) The time to strike at the head of the beast will soon be upon us! Focus your anger and hatred on %s!",
			"(Ressing) It is in the universe's best interest to re-originate %s should my analysis find systemic corruption. Do not interfere.",
			"(Ressing) This is the beginning AND the end, %s. None may enter the master's sanctum!",
			"(Ressing) %s, take this blessing and show these intruders a taste of our master's power.",
			"(Ressing) Do you yet grasp of the futility of your actions, %s?",
			"(Ressing) Twas a fierce battle, %s! Take a moment to rest and gather yer forces.",
			"(Ressing) %s, watch out because that's no ordinary gas cloud!",
			"(Ressing) Oh %s, you were always my favorite - next to Rotface. The good news is you left behind so much gas.",
			"(Ressing) Great news, everyone! %s is flowing again!",
			"(Ressing) Rise up, brother %s, and destroy our enemies!",
			"(Ressing) %s was merely a setback! With the power of the orb, Valanar will have his vengeance!",
			"(Ressing) Really, %s...? Is that all you've got? Such a pity.",
			"(Ressing) %s, you have been measured, and found wanting!",
			"(Ressing) Tragic... %s valiantly, but the beasts of Northrend triumphed. Let us observe a moment of silence for our fallen hero.",
		},
	},
	[4] = {
		["name"] = "Lyrics",
		["description"] = "Music lyrics quotes",
		["messages"] = {
			"(Ressing) - What is love? %s don't hurt me ... no more ...",
			"(Ressing) - Look at your young men fighting, Look at your women crying, Look at %s dying ...",
			"(Ressing) - Ich bin %s das kleine Krokodil. Komm aus aegypten, das liegt direkt am Nil !",
			"(Ressing) - %s told me her name was Billie Jean, as she caused a scene ...",		
			"(Ressing) - Oops, you did it again, %s ...",
			"(Ressing) - May I have your attention, please? Will the real %s please stand up?",
			"(Ressing) - If there's something strange in your neighborhood - Who you gonna call, %s ?",
			"(Ressing) - Mamma Mia - Here we go again, %s ...",
			"(Ressing) - Welcome to the Hotel California - such a lovely place, %s !",
			"(Ressing) - Why do we scream at each other? This is what it sounds like - When %s's cry",
			"(Ressing) - Resses for me, save all your resses for me - Bye, bye, %s bye, bye - Don't cry, honey, don't cry ...",
			"(Ressing) - Been spendin' most their lives, Livin' in the %s's paradise ...",
			"(Ressing) - There lived a %s man in Russia long ago, He was big and strong, in his eyes a flaming glow.",
			"(Ressing) - %s, you better shape up, cause I need a man. And my heart is set on you !",
			"(Ressing) - %s, cause your friends don't dance and if they don't dance, well they're no friends of mine !",
			"(Ressing) - So %s, tell me what you want, what you really really want ...",
			"(Ressing) - You were workin' as a waitress in a cocktail bar when I met you, %s ...",
			"(Ressing) - And as the feeling grows, she brings flesh to my bones. And when %s is dead, I'm loving angels instead.",
			"(Ressing) - %s, Is this the real life? Is this just fantasy? Caught in a landslide - no escape from reality.",
			"(Ressing) - Yes %s, I can boogie, but I need a certain song ...",	
		},
	},
	[5] = {
		["name"] = "Dad Jokes",
		["description"] = "40 jokes of questionable quality.",
		["messages"] = {
			"(Ressing) %s, did you know Albert Einstein had a brother called Frank? Apparently, he was a real monster.",
			"(Ressing) %s stole my copy of Microsoft Office. But I will get it back - you have my Word!",
			"(Ressing) %s just opened a restaurant on the moon. Great food, no atmosphere.",
			"(Ressing) %s just watched a program about beavers. It was the best dam program on tv.",
			"(Ressing) %s was wondering why the frisbee kept looking bigger and bigger, and then it hit him.",
			"(Ressing) %s think Sundays are always a little sad, but the day before is a sadder day.",
			"(Ressing) %s got fired from the banana farm. He kept throwing away the bent ones.",
			"(Ressing) %s wasn't going to get a brain transplant. But then the doctor changed his mind.",
			"(Ressing) %s's wife told him to stop impersonating a flamingo. He had to put a foot down.",
			"(Ressing) \"I have a split personality\", said %s, being Frank.",
			"(Ressing) %s asked 10 people what LGTBQ standed for but couldn't get a straight answer!",
			"(Ressing) %s can't find his 'Gone in 60 seconds' DVD. It was here a minute ago.",
			"(Ressing) %s accidentally rubbed ketchup in his eyes. He now have Heinzsight.",
			"(Ressing) %s asked the librarian if books about paranoia were available. She responded \"They're right behind you!\"",
			"(Ressing) %s's IQ test results came back. They were negative.",
			"(Ressing) %s' doctor told him he is going deaf. The news was hard for him to hear.",
			"(Ressing) The best gift I ever received from %s was a broken drum. You can't beat that.",
			"(Ressing) %s, how can you whisper people across the continent, but only yell 30 yards?",
			"(Ressing) %s didn't get any training as a garbage man. He just have to pick it up as he went along.",
			"(Ressing) %s picked a 8 character password: Show White and the Seven Dwarfs.",

			"(Ressing) %s considered having his family for Thanksgiving, but decided to stick with turkey.",
			"(Ressing) %s, what did one plate say to another plate? Tonight, dinner's on me.",
			"(Ressing) %s was kidnapped by mimes once. They did unspeakable things to that poor %c.",
			"(Ressing) Spring is here! %s got so excited he wet his plants.",
			"(Ressing) %s, what did the mayonnaise say when the refrigerator door was opened? Close the door, I'm dressing!",
			"(Ressing) %s, don't buy anything with velcro, It's a total rip-off.",
			"(Ressing) %s is reading a book about anti-gravity. It's impossible to put down.",
			"(Ressing) To the guy in the wheel chair who killed %s: You can hide, but you cannot run!",
			"(Ressing) %s, what is the scariest tree? BamBOO!",
			"(Ressing) I told %s's mother she drew on her eyebrows too high. She seemed surprised.",
			"(Ressing) %s quit his job as a standup comedian on Hawaii. The audience only responds in a low ha.",
			"(Ressing) %s gave his father his 50th birthday card. He looked at his son: -\"You know, one would have been enough.\"",
			"(Ressing) Why do %s take an extra pair of socks when he go golfing? In case he get a hole in one.",
			"(Ressing) %s broke his wrist last week, on the other hand he is okay.",
			"(Ressing) %s gave away all his used batteries today. Free of charge!",
			"(Ressing) %s, what character from Star Wars works at a restaurant? Darth Waiter.",
			"(Ressing) %s owe a lot to the sidewalks. They've been keeping him off the streets for years.",
			"(Ressing) %s sued an airline company after it lost his luggage. Sadly, he lost his case.",
			"(Ressing) %s changed his iPod's name to Titanic. It's syncing now.",
			"(Ressing) %s just joined the amateur autopsy club. Tuesday is open Mike night!",
		},
	},	
	[6] = {
		["name"] = "Dad Jokes",
		["description"] = "40 more jokes. Same low quality.",
		["messages"] = {		
			"(Ressing) %s, did you hear about the surgeon who enjoyed performing quick surgeries on insects? He did one on the fly.",		
			"(Ressing) %s, don't spell \"part\" backwards. It's a trap!",
			"(Ressing) %s, what's the difference between a hippo and a zippo? One is really heavy and the other's a little lighter.",
			"(Ressing) %s, there is a fine line between a numerator and a denominator. Only a fraction of people will get this!",
			"(Ressing) %s just got fired from the keyboard factory. He was not doing enough shifts.",
			"(Ressing) %s searched for a lighter on Amazon, but all he could find were 6,000 matches.",
			"(Ressing) %s invented the shovel. It was a ground-breaking invention.",
			"(Ressing) There's only one thing %s can't deal with, and that's a deck of cards glued together.",
			"(Ressing) %s have a fear of speed bumps, but is slowly getting over it.",
			"(Ressing) %s have a fear of elevators, but have now taking steps to avoid it.",
			"(Ressing) %s, did you hear about the cartoonist found dead at his home? Details are sketchy.",
			"(Ressing) %s, what does \"idk\" stand for? Everyone I ask says, \"I don't know.\"",
			"(Ressing) %s says that England doesn't have a kidney bank. But it does have a Liverpool.",
			"(Ressing) %s is making apocalypse jokes like there is no tomorrow!",
			"(Ressing) %s thinks sausage puns are the wurst.",
			"(Ressing) %s, tip of the day: Never discuss infinity with a mathematician, they can go on about it forever.",
			"(Ressing) %s met some aliens from outer space. They were pretty down to Earth.",
			"(Ressing) I thought I saw a spider on my laptop, but %s said it was just a bug.",
			"(Ressing) %s bought a wooden whistle but it wooden whistle.",
			"(Ressing) %s freed some aquatic mammals from cages in zoo. It was otter chaos.",
			
			"(Ressing) %s hate negative numbers and will stop at nothing to avoid them.",
			"(Ressing) %s, do you need an ark? I Noah guy!",
			"(Ressing) %s, how did Darth Vader know what Luke got him for Christmas? He felt his presents!",
			"(Ressing) What time did %s go to the dentist? Tooth hurt-y!",
			"(Ressing) %s ... do I enjoy making courthouse puns? Guilty.",
			"(Ressing) %s loves algebra and maybe a little calculus, but geometry is where he draw the line.",
			"(Ressing) %s got angry when I told him \"Sky is the limit for you\". He wants to be an astronaut.",
			"(Ressing) %s, what kind of noise does a witch's vehicle make? Brrrooomm, brrrooom",
			"(Ressing) Cosmetic surgery used to be such a taboo subject. Now %s talks about Botox and nobody raises an eyebrow.",
			"(Ressing) %s, how did the pirate get his ship so cheap? It was on sail...",
			"(Ressing) %s, the problem with kleptomaniacs is that they always take things literally.",
			"(Ressing) %s asked what Deja Vu means. I think I expained him earlier.",
			"(Ressing) %s, most people are shocked when they find out how bad I am as an electrician.",
			"(Ressing) %s, people who use selfie sticks really need to have a good, long look at themselves.",
			"(Ressing) %s, recent study has found that women who carry a little extra weight live longer than the men who mention it.",
			"(Ressing) %s, last night my girlfriend was complaining that I never listen to her... or something like that.",
			"(Ressing) %s, what do you call a laughing jar of mayonnaise? LMAYO.",
			"(Ressing) %s, I didn't think orthopedic shoes would help, but I stand corrected.",
			"(Ressing) %s was explaining electricity to me, but I was like, \"Watt?\"",
			"(Ressing) %s has been thinking about taking up meditation. It's better than sitting around doing nothing.",
		}
	},
	[7] = {
		["name"] = "Warcraft Jokes",
		["description"] = "Jokes from the Warcraft universe",
		["messages"] = {
			"(Ressing) %s, what do Rogues and noobs have in common? They both pick locks.",
			"(Ressing) %s, what do you call a Druid who melees in tree form? A combat log.",
			"(Ressing) %s just spend 200 DKP for a belt that doesn't fit! What a huge waist!",
			"(Ressing) %s is finally upgrading from 1080p to 4K in January. It's his new years resolution.",
			"(Ressing) %s, why did the Enchanter have to clean out his bank? Because it was full of dust!",
			"(Ressing) %s, why do you even want a bug mount? I prefer a working one!",
			"(Ressing) %s, why didn't the Warrior cross the road? No path available.",
			"(Ressing) %s, I love my class trainer. He respecs me.",
			"(Ressing) %s was hit by Sapphiron and got cooled to absolute zero. He's 0k now.",
			"(Ressing) %s is not playing Rogue becase he like daggers. He is doing it for kicks.",
			"(Ressing) %s, what do you call a Tauren Rogue? Invisibull.",
			"(Ressing) %s, what did the feral Druid trainer tell his students? Bear with me!",
			"(Ressing) %s, what do you call it when Paladins refuse to work? Crusader Strike!",
			"(Ressing) %s won a pair of gloves, but they're both lefts, which on one hand is great but on the other just not right.",
			"(Ressing) I thought I saw a spider pack in AQ40, but %s said it was just a bug.",
			"(Ressing) %s, how does a Druid cut his hair? Eclipse it.",
			"(Ressing) %s, how did the Paladin start losing weight? He was eating light.",
			"(Ressing) %s, where does Ragnaros go for his back treatments? The pyro-practor.",
			"(Ressing) %s, why do Hunters get smashed in bars? Because they’re always multi-shotting.",
			"(Ressing) %s, what do you call a Gnome Priest? A compact disc.",
		},
	},
	[8] = {
		["name"] = "Simple",
		["description"] = "Simple resurrection message",
		["messages"] = {
			"Resurrecting %s ...",
		},
	}
};